Fix State Logic for Inputs so the Server can Overwrite
GooeyAI/gooey-gui pull request #16
Opened 2023-12-21 01:19 UTC by SanderGi

Fixes many bugs with the displayed state not matching the server state. Allows functionality like reset to default on copilot integrations and email import on QR without hacky keyswaps

2023-12-21 10:14 UTC, devxpy commented
Awesome

2023-12-21 10:39 UTC, devxpy commented on app/gooeyFileInput.tsx
> +        element.value = state[name];
This should be json encoded. Please test before pushing

```
SyntaxError: Unexpected token h in JSON at position 0
    at JSON.parse (<anonymous>)
    at file (/Users/dev/WebstormProjects/gooey-remix/app/dataTable.tsx:164:13)
    at action2 (/Users/dev/WebstormProjects/gooey-remix/app/app.tsx:231:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /Users/dev/WebstormProjects/gooey-remix/node_modules/@sentry/src/utils/instrumentServer.ts:207:1
    at Object.callRouteActionRR (/Users/dev/WebstormProjects/gooey-remix/node_modules/@remix-run/server-runtime/dist/data.js:35:16)
    at callLoaderOrAction (/Users/dev/WebstormProjects/gooey-remix/node_modules/@remix-run/router/router.ts:3550:16)
    at submit (/Users/dev/WebstormProjects/gooey-remix/node_modules/@remix-run/router/router.ts:2817:16)
    at queryImpl (/Users/dev/WebstormProjects/gooey-remix/node_modules/@remix-run/router/router.ts:2752:22)
    at Object.queryRoute (/Users/dev/WebstormProjects/gooey-remix/node_modules/@remix-run/router/router.ts:2702:18)
    at handleDataRequestRR (/Users/dev/WebstormProjects/gooey-remix/node_modules/@remix-run/server-runtime/dist/server.js:63:20)
    at requestHandler (/Users/dev/WebstormProjects/gooey-remix/node_modules/@remix-run/server-runtime/dist/server.js:37:18)
    at /Users/dev/WebstormProjects/gooey-remix/node_modules/@sentry/src/utils/instrumentServer.ts:411:1
    at /Users/dev/WebstormProjects/gooey-remix/node_modules/@remix-run/express/dist/server.js:39:22

```

2023-12-21 10:44 UTC, devxpy commented on app/gooeyFileInput.tsx
> +  state?: Record<string, any>;
Maybe this doesn't need to be optional?

2023-12-21 10:44 UTC, devxpy commented on app/base.tsx
> +  state?: Record<string, any>;
This too

2023-12-21 10:45 UTC, devxpy commented on app/base.tsx
> +          useEffect(() => {
I don't think using useEffect inside a conditional clause is allowed, put this in a separate component  https://react.dev/reference/react/useEffect
<img width="1049" alt="image" src="https://github.com/GooeyAI/gooey-ui/assets/19492893/6c3b2fce-67e8-48df-af9a-4fda891ccfa1">

2023-12-21 17:07 UTC, SanderGi commented on app/gooeyFileInput.tsx
> +        element.value = state[name];
I did test every input, I just didn't think to test in conjunction with unchanged inputs like the table. I'll fix this and remember for next time

2023-12-21 17:09 UTC, SanderGi commented on app/base.tsx
> +          useEffect(() => {
Weird that it worked then 🤔 -- possibly it's because the conditional is either always true or always false since we don't dynamically change the input type? I'll move it into a separate component

2023-12-30 01:17 UTC, SanderGi commented on app/gooeyFileInput.tsx
> +  state?: Record<string, any>;
Fixed: [67f99d8](https://github.com/GooeyAI/gooey-ui/pull/16/commits/67f99d88e01049e7be321ec59507b8ddceb0cdbf)

2023-12-30 01:17 UTC, SanderGi commented on app/base.tsx
> +  state?: Record<string, any>;
Fixed: [67f99d8](https://github.com/GooeyAI/gooey-ui/pull/16/commits/67f99d88e01049e7be321ec59507b8ddceb0cdbf)

2023-12-30 01:31 UTC, SanderGi commented on app/base.tsx
> +          useEffect(() => {
Refactored: [f7ae724](https://github.com/GooeyAI/gooey-ui/pull/16/commits/f7ae7243a5b116cff2731300a7e4e6ddf7c597c3)

2023-12-30 10:03 UTC, SanderGi commented on app/gooeyFileInput.tsx
> +        element.value = state[name];
I believe every bug has been fixed now (spent a few hours testing everything but could still have missed something): [bac2016](https://github.com/GooeyAI/gooey-ui/pull/16/commits/bac2016862ffa14eb86c670c4d557939feafa0be)

2024-01-03 16:00 UTC, devxpy commented
https://github.com/GooeyAI/gooey-ui/assets/19492893/dc51b2c3-1426-4bd2-8000-f8bce16ff4b5

2024-01-03 16:58 UTC, SanderGi commented
> IMG_3498.mov

Love the music lol. Here's the fix: [9aa4175](https://github.com/GooeyAI/gooey-ui/pull/16/commits/9aa4175d2c6831cb00d1104cafa13419cef8ee5a)

https://github.com/GooeyAI/gooey-ui/assets/97496861/092f91b9-8886-4c99-81ff-035991fd16c1

2024-01-06 21:59 UTC, devxpy commented
Stress test your UIs like you’re a drunk teenager

https://github.com/GooeyAI/gooey-ui/assets/19492893/fbc33285-2393-4110-aebe-bad509c6d34d

2024-01-06 22:17 UTC, devxpy commented
Also test by setting network speed to slow 3g from chrome dev console

2024-01-06 22:29 UTC, devxpy commented
> Stress test your UIs like you’re a drunk teenager
> 
>  IMG_3543.mov

Actually this might be because of the limit on that slider?

2024-01-06 22:34 UTC, devxpy requested changes

2024-01-06 22:34 UTC, devxpy commented on app/base.tsx
> +      }, [state[name], defaultValue]);
<img width="1121" alt="image" src="https://github.com/GooeyAI/gooey-ui/assets/19492893/6a642067-89d0-4411-a47a-acf389bb7514">

2024-01-07 04:58 UTC, SanderGi commented
> > Stress test your UIs like you’re a drunk teenager
> > IMG_3543.mov
> 
> Actually this might be because of the limit on that slider?

It is indeed because of the limits and steps on number inputs. To make them easier to type in, I've made them postpone the autocorrection and submit until the user focuses something else (e.g. hit submit or click the background): [c726035](https://github.com/GooeyAI/gooey-ui/pull/16/commits/c726035223a99d70abcb6f6e288266c656ddbca9)

2024-01-07 05:07 UTC, SanderGi commented on app/base.tsx
> +      }, [state[name], defaultValue]);
In my defence, our linter has identified about a billion problems (not just for this PR) so I didn't see this one lol:
<img width="749" alt="image" src="https://github.com/GooeyAI/gooey-ui/assets/97496861/1eee5fc1-7da2-4380-8072-c6c84e8594ac">

I believe this specific one should be fixed now: [5bc46f1](https://github.com/GooeyAI/gooey-ui/pull/16/commits/5bc46f175c11458952568d937322601af51906af)

2024-01-08 14:50 UTC, devxpy commented
Reverting this, because it makes it so that the form doesn't submit unless you shift focus. Use debounce instead to detect when someone has _stopped typing_, instead of _shifted focus_ to another input widget

2024-01-08 14:51 UTC, devxpy commented
<img width="1110" alt="image" src="https://github.com/GooeyAI/gooey-ui/assets/19492893/c02c2c00-80f3-4d95-ad62-d506563bfcaa">

2024-01-08 18:06 UTC, SanderGi commented
> Reverting this, because it makes it so that the form doesn't submit unless you shift focus. Use debounce instead to detect when someone has _stopped typing_, instead of _shifted focus_ to another input widget

I tried debounce but it did not work if people type slowly enough. The problem is that the number input does autocorrection of invalid input which doesn’t make sense while someone is in the middle of typing. This is different from the text inputs. Besides, we really don’t need a submit until focus shifts away since we don’t save the data until the user hits submit or does something else on the site anyways

2024-01-08 18:08 UTC, SanderGi commented
> <img alt="image" width="1110" src="https://private-user-images.githubusercontent.com/19492893/294940172-c02c2c00-80f3-4d95-ad62-d506563bfcaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MzczMDcsIm5iZiI6MTcwNDczNzAwNywicGF0aCI6Ii8xOTQ5Mjg5My8yOTQ5NDAxNzItYzAyYzJjMDAtODBmMy00ZDk1LWFkNjItZDUwNjU2M2JmY2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDE4MDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOTYyZmE5ZGExYjA2NmZiYTI5OTE1MTUyYzc3ZGIzMWNjMDRiYWRiNmYxODgzZDI5MTVhZTJlODQxNDEwZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Trtj5TOBYOQUXfOwj29IXhKV5i5hr6x8DR7UBLfJAM4">

ESLint is technically wrong here since we do not change component type dynamically so the hook will always be called and in the same order. I’ll refactor into a component though

2024-02-09 16:18 UTC, merged